DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
  DName				VARCHAR(25) 	NOT NULL,
  DNumber			INTEGER(4)		NOT NULL,
  Mgr_SSN			CHAR(9), 		 
  Mgr_start_date	DATE,
  CONSTRAINT DEPT_PK
	PRIMARY KEY (DNumber),
  CONSTRAINT DEPT_UNIQUE
	UNIQUE (DName)
);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPT_MGR_FK
	FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(SSN)
		ON DELETE SET NULL
		ON UPDATE CASCADE;