DROP TABLE IF EXISTS DEPENDENT;
CREATE TABLE DEPENDENT (
  ESSN           CHAR(9)		NOT NULL,
  Dependent_name VARCHAR(15)	NOT NULL,
  Sex            CHAR,
  BDate          DATE,
  Relationship   VARCHAR(8),
  CONSTRAINT DEPENDENT_PK
	PRIMARY KEY (ESSN,Dependent_name)
);

ALTER TABLE DEPENDENT
ADD CONSTRAINT DEPENDENT_FK
  FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;