DROP TABLE IF EXISTS DEPT_LOCATIONS;
CREATE TABLE DEPT_LOCATIONS (
  DNumber		INTEGER(4)		NOT NULL,
  DLocation		VARCHAR(15)		NOT NULL,
  CONSTRAINT DEPT_LOC_PK
	PRIMARY KEY (DNumber, DLocation)
);

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT DEPT_LOC_FK
	FOREIGN KEY (DNumber) REFERENCES DEPARTMENT(DNumber)
		ON DELETE RESTRICT
		ON UPDATE CASCADE;