DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
  FName		VARCHAR(15)		NOT NULL, 
  MInit		VARCHAR(1),
  LName		VARCHAR(15)		NOT NULL,
  SSN		CHAR(9)			NOT NULL,
  BDate		DATE,
  Address	VARCHAR(50),
  Sex		CHAR,
  Salary	DECIMAL(10,2)	CHECK (Salary > 0),
  Super_SSN	CHAR(9),
  DNo		INTEGER(4)		DEFAULT 1,
  CONSTRAINT EMP_PK
	PRIMARY KEY (SSN)
);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMP_SUPER_FK
	FOREIGN KEY (Super_SSN) REFERENCES EMPLOYEE(SSN)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
ADD CONSTRAINT EMP_DEPT_FK
	FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNumber)
		ON DELETE SET NULL
		ON UPDATE CASCADE;
		
