DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT (
  PName      VARCHAR(25) 	NOT NULL,
  PNumber    INTEGER(4)		NOT NULL,
  PLocation  VARCHAR(15),
  DNum       INTEGER(4), 	
  CONSTRAINT PROJECT_PK
	PRIMARY KEY (PNumber),
  CONSTRAINT PROJECT_UNIQUE
	UNIQUE (PName)
);

ALTER TABLE PROJECT
ADD CONSTRAINT PROJECT_FK
  FOREIGN KEY (DNum) REFERENCES DEPARTMENT(DNumber)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;