DROP TABLE IF EXISTS WORKS_ON;
CREATE TABLE WORKS_ON (
  ESSN   CHAR(9)		NOT NULL,
  PNo    INTEGER(4)		NOT NULL,
  Hours  DECIMAL(4,1),
  CONSTRAINT WORKS_ON_PK
	PRIMARY KEY (ESSN,PNo)
);

ALTER TABLE WORKS_ON
ADD CONSTRAINT WORKS_ON_SSN_FK
  FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN)
	ON DELETE RESTRICT
	ON UPDATE CASCADE,
ADD CONSTRAINT WORKS_ON_PNO_FK
  FOREIGN KEY (PNo) REFERENCES PROJECT(PNumber)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;